version: '3.8'
services:
  postgresql:
    image: postgres:14
    environment:
      POSTGRES_USER: hackaton
      POSTGRES_PASSWORD: hackaton
      POSTGRES_DB: hackaton
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  php:
    build: ./php
    ports:
      - "8081:80"
    depends_on:
      - postgresql
    volumes:
      - ./php:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default

  python:
    build: ./python
    ports:
      - "8000:8000"
    depends_on:
      - postgresql

  go:
    build: ./go
    ports:
      - "8082:8080"
    depends_on:
      - postgresql

  nodejs:
    build: ./nodejs
    ports:
      - "3000:3000"
    depends_on:
      - postgresql

volumes:
  pgdata:
